export default {
  mainDiv: ``,
  itemWrapper: ``,
  optionContainer: ``,
  optionWrapper: ``,
  multipleChoiceItemContent: ``,
  narrowOpenItemContent: ``,
  wideOpenItemContent: ``,
  essayItemContent: ``,
  upperContent: ``,
  submitMessageDiv: ``,
  answerPaper: ``,
  answerField: ``,
  quizBody: ``,
  stepper: ``,
  submitGroup: ``,
  messageGroup: ``,
  questionBlockWrapper: ``,
  buttonWrapper: ``,
  peerReviewContainer: ``,
  peerReviewGuidance: ``,
  peerReviewForm: ``,
  receivedPeerReviews: ``,
}
