version: '3.8'

services:
  backend:
    restart: always 
    build: 
      context: ./packages/backendv2
      dockerfile: development.Dockerfile
    ports:
      - 3003:3003
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
  
  example:
    restart: always
    build:
      context: ./packages/moocfi-quizzes
      dockerfile: development.Dockerfile
    ports:
      - 1234:1234
    depends_on:
      - backend

  dashboard:
    restart: always
    build: 
      context: ./packages/quizzes-dashboard
      dockerfile: development.Dockerfile
    depends_on:
      - backend
    ports:
      - 5000:5000

  postgres:
    image: postgres:11-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    container_name: redis
    restart: always 

volumes:
  postgres: ~