FROM node:11-alpine as builder

RUN apk --no-cache update \
&& apk --no-cache add g++ make bash zlib-dev libpng-dev \
&&  rm -fr /var/cache/apk/*

COPY --chown=node . /app

USER node

WORKDIR /app

RUN yarn install

ENV NODE_ENV=production

WORKDIR /app/packages/dashboard

RUN yarn build

FROM nginx:1.15-alpine

COPY --from=builder /app/packages/dashboard/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
