FROM node:11-alpine

RUN apk --no-cache update \
&& apk --no-cache add g++ make bash zlib-dev libpng-dev postgresql-client redis python2 \
&&  rm -fr /var/cache/apk/*

COPY --chown=node . /app

USER node

WORKDIR /app/packages/moocfi-quizzes

RUN yarn install
